# -*- coding: utf-8 -*-
"""PythonifStatementExcerciseTodayMore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QZEAu48O5HFW3yADVHp3JtCSZLaUkbIl
"""

print("Hello World")

age = int(input("What is your age?"))

if age < 18:
  print("you are not eligible to vote")
else:
  print("You are eligible to vote !")

name = input("What is your name?")
age = int(input("How old are you , {0}?".format(name)))

# if age >= 18:
#   print("You are old enough to vote ")
#   print("Please put an X in thee box ")
# else:
#   print("Please come back in {0} years ".format(18 - age))
  
if age < 18: 
  print("Please come back in {0} years ".format(18 - age))


elif age >= 99:
  print("You are senior citizen you have to votes")
  

else:
  print("You are old enough to vote ")
  print("Please put an X in thee box ")

"""Python Guessing Game: 

1.  If Statement 
2.  Elif 


"""

answer_guess = 6


print("Enter The Guess number between 1 and 10: ")
guess_num = int(input())

if guess_num > answer_guess:
  print("The Guess is higher")
  guess_num = int(input())
if guess_num == answer_guess:
    print("Thats the game you won")

elif guess_num < answer_guess:
  print("The Guess is lower")
  guess_num = int(input())
if guess_num == answer_guess:

  print("Thats the game you won")



elif guess_num == 0:

  print("Invalid Number Game over refresh the program!")

#Progess 
answer = 5

print("Please guess number between 1 and 10: ")
guess = int(input())

if guess < answer:
    print("Please guess higher")
    guess = int(input())
    if guess == answer: 
        print("Well done, you guessed it")
    else:
        print("Sorry, Invalid Guess")
        
elif guess > answer:
    print("Please Guess Lower")
    guess = int(input())
    if guess == answer:
        print("Well done, you guessed it")
    else:
        print("Sorry, Invalid Guess")
    
else:
    print("You won the game")


answer = 4

print("Enter the Number between 1 and 10: ")

guess = int(input())

if guess != answer:
  if guess > answer:
    print("The Guess is higher")
    guess = int(input())
    if guess == answer:
      print("Guessed it correctly")
    else:
      print("Invalid Guess")

  if guess < answer:
    print("The Guess is lower")
    guess = int(input())
    if guess == answer:
      print("Guessed it correctly")
    else:
      print("Invalid Guess")
  
else:
  print("Well done you guess it correctly on first try:: ")

answer = 4

print("Enter the Number between 1 and 10: ")

guess = int(input())

if guess == answer:
   print("Well done you guess it correctly on first try:: ")
else:
  if guess > answer:
    print("The Guess is higher")
    guess = int(input())
    if guess == answer:
      print("Guessed it correctly")
    else:
      print("Invalid Guess")

  if guess < answer:
    print("The Guess is lower")
    guess = int(input())
    if guess == answer:
      print("Guessed it correctly")
    else:
      print("Invalid Guess")